sudo: required
language: node_js
node_js:
- node
- --lts
branches:
  only:
  - master
env:
  global:
  - SAUCE_USERNAME=material-sauce
  - secure: kKeE1NPOab6DREAl1G84eNVe25QuBHL3S94UMZbFsiULGgbMuV8W5ZZ1F7V0qJaEA1diWsw2E+KCOXj5UkjJQMBn/tMIT7mRHsSrLqUfdKw1xbbz0S6ASZHTwKne9T0XyVoVbV42fsEl7zzUPlAeQYcrzdgbZtnPBh0RuyZyGp0BEAjihwgxDwNld3t/qKINKd6QsrGaW/viL8jGqk0cTQkfrg9GOFd1rWiIS2GtpmhyiNe5k8ENKG1d2fplGxycFWL9SMCgyXphNx2ggLUVIM8oFCXStSzjwGeAv0+wodonvTUe9rk/C+wxEy6ACPxbn2gpqfpfZSj8iMO53xX0QIC2+RjvpPfKH5Sq3GaeaBTNB3U2oR7ZSEuabq/5Wza4i3pkWYFDwNHwTuk8FYYt1C/XiM6QE4plvMd0T2BWndGje0cJ3KeWRM+6HROVAZWq4sGIkGnYVouguOJSON7b2O5ftaqMi6viYy50tzUDev6cDiEgoTTMnIuXYpbz+q/wCnzISugoyHrkgi7A7fNLHNd97rtBcMZmq2W++qsJLPT3mHy4H+vrsU6yhiKAY8igkfu3mf1G9BCDfmplLy2Yazt6kSoriP/xzZ0Puvqr2BdVmo1oPiy790MKAabQT8FaRf0alMSw+hWqOD811OgUWQMt8COSNaU6lm/pQvf/L4s=
addons:
  firefox: latest
  sauce_connect: true
  jwt:
    secure: kKeE1NPOab6DREAl1G84eNVe25QuBHL3S94UMZbFsiULGgbMuV8W5ZZ1F7V0qJaEA1diWsw2E+KCOXj5UkjJQMBn/tMIT7mRHsSrLqUfdKw1xbbz0S6ASZHTwKne9T0XyVoVbV42fsEl7zzUPlAeQYcrzdgbZtnPBh0RuyZyGp0BEAjihwgxDwNld3t/qKINKd6QsrGaW/viL8jGqk0cTQkfrg9GOFd1rWiIS2GtpmhyiNe5k8ENKG1d2fplGxycFWL9SMCgyXphNx2ggLUVIM8oFCXStSzjwGeAv0+wodonvTUe9rk/C+wxEy6ACPxbn2gpqfpfZSj8iMO53xX0QIC2+RjvpPfKH5Sq3GaeaBTNB3U2oR7ZSEuabq/5Wza4i3pkWYFDwNHwTuk8FYYt1C/XiM6QE4plvMd0T2BWndGje0cJ3KeWRM+6HROVAZWq4sGIkGnYVouguOJSON7b2O5ftaqMi6viYy50tzUDev6cDiEgoTTMnIuXYpbz+q/wCnzISugoyHrkgi7A7fNLHNd97rtBcMZmq2W++qsJLPT3mHy4H+vrsU6yhiKAY8igkfu3mf1G9BCDfmplLy2Yazt6kSoriP/xzZ0Puvqr2BdVmo1oPiy790MKAabQT8FaRf0alMSw+hWqOD811OgUWQMt8COSNaU6lm/pQvf/L4s=
